config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'cocktails#index'
  # resources :cocktails, only: %i[index show new create]

  resources :cocktails, only: %i[index show new create] do
    resources :doses, only: %i[new create] # edit update later if needed
  end

  resources :doses, only: %i[index show destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses

  # A cocktail must have a unique name.
  validates :name, presence: true, uniqueness: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  # A dose must have a description, a cocktail and an ingredient, and [cocktail, ingredient] pairings should be unique.
  validates :description, presence: true
  validates_associated :cocktail, :ingredient
  validates :cocktail, uniqueness: { scope: :ingredient }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses

  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :find_cocktail, only: [:show]

  def index
    @cocktails = Cocktail.all
    @dose = Dose.new
  end

  def show
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)

    if @cocktail.save
      redirect_to @cocktail
    else
      render :new
    end
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name)
  end

  def find_cocktail
    @cocktail = Cocktail.find(params[:id])
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  before_action :find_cocktail, only: %i[new create]

  def new
    @dose = Dose.new
  end

  def create
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktails_path
    else
      render :new
    end
  end

  def show
  end

  def destroy
    raise
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktails_path
  end

  private

  def find_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/index.html.erb
<div class="container">
  <div class="grid-container">
    <% @cocktails.each do |cocktail| %>
      <%= render 'shared/card', cocktail: cocktail, dose: @dose %>
    <% end %>
    <%= render 'shared/add-card' %>
  </div>
</div>

app/views/cocktails/new.html.erb
<h1>Name your Cocktail!</h1>

<%= simple_form_for(@cocktail) do |f| %>
  <%= f.input :name %>
  <%= f.submit 'Create!', class: 'btn btn-primary' %>
<% end %>

app/views/cocktails/show.html.erb
<div class="container">
  <h1>Welcome to <%= @cocktail.name %> Page</h1>

  <ul>
    <% @cocktail.doses.each do |dose| %>
      <li>
        <%= dose.ingredient.name %> - <%= dose.description %>
        [<%= link_to "Delete",
            dose_path(dose),
            method: :delete,
            data: { confirm: "Are you sure?" } %>]
      </li>
    <% end %>
  </ul>

  <%= link_to 'Add a dose', new_cocktail_dose_path(@cocktail) %>
</div>

app/views/doses/new.html.erb
<h1>What's inside a <%= @cocktail.name %></h1>

<%= simple_form_for([@cocktail, @dose]) do |f| %>
  <%= f.input :description %>
  <%= f.association :ingredient %>
  <%= f.submit 'Add your poison!', class: 'btn btn-primary' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <div class="banner">
      <h1>Mister Bartender</h1>
    </div>

    <div class="background-wrapper">
      <%= yield %>
    </div>

    <footer>

    </footer>
  </body>
</html>

app/views/shared/_add-card.html.erb
<%= link_to new_cocktail_path,
  class: 'card-add__wrapper' do %>
    <div class="card-add__image"></div>
    <div class="card-add__content">
      <h2>Add a Cocktail</h2>

        <i class="fas fa-plus"></i>

    </div>
<% end %>

app/views/shared/_card.html.erb
<div class="card__wrapper js-card-flip">
  <div class="card__flip-card">

    <div class="card-front__wrapper">
      <div class="card-front__image"></div>
      <div class="card-front__content">
        <h2><%= cocktail.name %></h2>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Optio sed, illo, blanditiis ullam a qui? Ducimus expedita.</p>

        <%= link_to 'View Page', cocktail_path(cocktail) %>
      </div>
    </div>

    <div class="card-back__wrapper">
      <div class="card-back__content">
        <h3><%= cocktail.name %></h3>
        <ul class="card-back__doses-list">
          <% cocktail.doses.each do |dose| %>
            <li>
              <%= dose.ingredient.name %> - <%= dose.description %>
            </li>
          <% end %>
        </ul>
      </div>
      <%= simple_form_for([cocktail, @dose]) do |f| %>
        <%= f.input :description, placeholder: 'Description here', label: false %>
        <%= f.association :ingredient, prompt: 'Select an ingredient', label: false %>
        <%= f.submit 'Add a dose', class: 'btn btn-add-dose' %>
      <% end %>
    </div>

  </div>
</div>